server:
  port: 8086

dubbo:
  application:
    #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: provider
    id: provider
  registry:
    #注册中心配置，用于配置连接注册中心相关信息。
    id: zookeeper
    address: zookeeper://127.0.0.1:2181
#    id: my-registry
#    address: N/A
  #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
  protocol:
    id: dubbo
    name: dubbo
    port: 20800
    status: server
  #服务暴露与发现消费所在的package
  scan:
    basePackages: com.example.service.impl

demo:
  service:
    version: 1.0.0