server:
  port: 8087

dubbo:
  application:
    #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    id: comsumer
    name: consumer
  #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
  protocol:
    id: dubbo
    name: dubbo
    port: 20800
  #服务暴露与发现消费所在的package
#  scan: com.example.service

demo:
  service:
    version: 1.0.0